version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: numwatch_postgres
    environment:
      POSTGRES_DB: numwatch_db
      POSTGRES_USER: numwatch_user
      POSTGRES_PASSWORD: numwatch_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U numwatch_user -d numwatch_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: numwatch_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://numwatch_user:numwatch_pass@postgres:5432/numwatch_db
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./responseData.json:/app/responseData.json
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: numwatch_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data: