# Render Blueprint for NumWatch Application
services:
  # Backend API Service
  - type: web
    name: numwatch-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false  # Set manually in Render dashboard
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://numwatch-frontend.onrender.com
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false

  # Frontend Static Site
  - type: static
    name: numwatch-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://numwatch-backend.onrender.com